version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: prueba_backend
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: api_usuarios
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGO_URI: mongodb://admin:password@mongo:27017/prueba_backend?authSource=admin
    volumes:
      - .:/usr/src/app
    command: npm run dev

volumes:
  mongo_data:
    driver: local
